# Generated by Django 3.2.12 on 2022-03-14 11:56

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis_Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100, null=True)),
                ('tempo', models.CharField(max_length=3, null=True)),
                ('file', models.FileField(upload_to='')),
                ('session_code', models.CharField(default=api.models.generate_user_code, max_length=10, unique=True)),
            ],
        ),
    ]
