# Generated by Django 3.2.12 on 2022-03-15 14:42

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('tempo', models.CharField(blank=True, max_length=3)),
                ('rate', models.CharField(max_length=6)),
                ('wav_data', models.BinaryField()),
                ('session_code', models.CharField(default=api.models.generate_user_code, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('tempo', models.CharField(blank=True, max_length=3)),
                ('file', models.FileField(upload_to='')),
                ('session_code', models.CharField(default=api.models.generate_user_code, max_length=10, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Analysis_Session',
        ),
    ]
