# Generated by Django 3.2.12 on 2022-03-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_analysissession_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysissession',
            old_name='wav_data',
            new_name='wav_data_b64',
        ),
        migrations.AddField(
            model_name='analysissession',
            name='wav_data_json',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
