# Generated by Django 3.2.12 on 2022-03-16 11:55

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220316_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysissession',
            name='wav_data_json',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
