# Generated by Django 3.2.12 on 2022-03-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_noteonsetcalculator'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='note_onsets_b64',
            field=models.BinaryField(null=True),
        ),
    ]
