# Generated by Django 3.2.12 on 2022-03-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_analysissession_note_onsets_b64'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='threshold',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
