# Generated by Django 3.2.12 on 2022-03-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_analysissession_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteonsetcalculator',
            name='session_code',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
