# Generated by Django 3.2.12 on 2022-03-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_noteonsetcalculator_session_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysissession',
            name='wav_data_b64',
        ),
        migrations.AddField(
            model_name='analysissession',
            name='averager',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='wav_data_json_for_js',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
