# Generated by Django 3.2.12 on 2022-03-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220318_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysissession',
            name='note_onsets_b64',
        ),
        migrations.AddField(
            model_name='analysissession',
            name='note_onsets_json',
            field=models.JSONField(null=True),
        ),
    ]
