# Generated by Django 3.2.12 on 2022-03-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220318_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysissession',
            name='wav_data_json_for_js',
        ),
        migrations.AddField(
            model_name='analysissession',
            name='filepath',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
